// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PawCare.Server.Persistence;

#nullable disable

namespace PawCare.Server.Migrations
{
    [DbContext(typeof(PawCareDbContext))]
    [Migration("20260630152127_SeedVeterinarians")]
    partial class SeedVeterinarians
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PawCare.Server.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "vet-seed-0001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "vet-seed-0001",
                            Email = "sarah.mitchell@pawcare-vet.test",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAH.MITCHELL@PAWCARE-VET.TEST",
                            NormalizedUserName = "SARAH.MITCHELL@PAWCARE-VET.TEST",
                            PasswordHash = "AQAAAAIAAYagAAAAEJCZc3vwf1fiRepOISIEe1oZtgbyM7WaskhzadRRo198RUfp1jwiQmMPPd7ykWIOhA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "vet-seed-0001",
                            TwoFactorEnabled = false,
                            UserName = "sarah.mitchell@pawcare-vet.test"
                        },
                        new
                        {
                            Id = "vet-seed-0002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "vet-seed-0002",
                            Email = "daniel.okafor@pawcare-vet.test",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DANIEL.OKAFOR@PAWCARE-VET.TEST",
                            NormalizedUserName = "DANIEL.OKAFOR@PAWCARE-VET.TEST",
                            PasswordHash = "AQAAAAIAAYagAAAAEGPeMNESI1AyHiEnxFcZgGJuAXVJyQ5vDemZQg1zZKW78BWHI1SbNUnWvwYmqM+sgw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "vet-seed-0002",
                            TwoFactorEnabled = false,
                            UserName = "daniel.okafor@pawcare-vet.test"
                        },
                        new
                        {
                            Id = "vet-seed-0003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "vet-seed-0003",
                            Email = "priya.nair@pawcare-vet.test",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PRIYA.NAIR@PAWCARE-VET.TEST",
                            NormalizedUserName = "PRIYA.NAIR@PAWCARE-VET.TEST",
                            PasswordHash = "AQAAAAIAAYagAAAAEIy2tffpV/UNTeU5IIryMPdrgWBprd1bXbEAIjWMJMv+NcJlsi9KWxpfnz1Cse3YsQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "vet-seed-0003",
                            TwoFactorEnabled = false,
                            UserName = "priya.nair@pawcare-vet.test"
                        },
                        new
                        {
                            Id = "vet-seed-0004",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "vet-seed-0004",
                            Email = "james.whitfield@pawcare-vet.test",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JAMES.WHITFIELD@PAWCARE-VET.TEST",
                            NormalizedUserName = "JAMES.WHITFIELD@PAWCARE-VET.TEST",
                            PasswordHash = "AQAAAAIAAYagAAAAEPG5tvVWZ35M5290SdZJWmepJmiD4cn8nr39wEBooj6wOteeaVkiBaR1O3UFIPavIA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "vet-seed-0004",
                            TwoFactorEnabled = false,
                            UserName = "james.whitfield@pawcare-vet.test"
                        },
                        new
                        {
                            Id = "vet-seed-0005",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "vet-seed-0005",
                            Email = "elena.vasquez@pawcare-vet.test",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ELENA.VASQUEZ@PAWCARE-VET.TEST",
                            NormalizedUserName = "ELENA.VASQUEZ@PAWCARE-VET.TEST",
                            PasswordHash = "AQAAAAIAAYagAAAAEG0FQR/Zn2C/Xw503lmL+QxN26Gpb9ekt66lOSARPkKjKV/AmJmn6zfYCGcGSbxWDQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "vet-seed-0005",
                            TwoFactorEnabled = false,
                            UserName = "elena.vasquez@pawcare-vet.test"
                        });
                });

            modelBuilder.Entity("PawCare.Server.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VeterinarianId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("PawCare.Server.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBirthDateEstimated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("PetOwners");
                });

            modelBuilder.Entity("Veterinarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("numeric");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Veterinarians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "vet-seed-0001",
                            ConsultationFee = 50.00m,
                            FirstName = "Sarah",
                            LastName = "Mitchell",
                            LicenseNumber = "VET-0001",
                            Specialty = "GeneralPractice",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = "vet-seed-0002",
                            ConsultationFee = 120.00m,
                            FirstName = "Daniel",
                            LastName = "Okafor",
                            LicenseNumber = "VET-0002",
                            Specialty = "Surgery",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 3,
                            ApplicationUserId = "vet-seed-0003",
                            ConsultationFee = 65.00m,
                            FirstName = "Priya",
                            LastName = "Nair",
                            LicenseNumber = "VET-0003",
                            Specialty = "Dermatology",
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 4,
                            ApplicationUserId = "vet-seed-0004",
                            ConsultationFee = 150.00m,
                            FirstName = "James",
                            LastName = "Whitfield",
                            LicenseNumber = "VET-0004",
                            Specialty = "Cardiology",
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 5,
                            ApplicationUserId = "vet-seed-0005",
                            ConsultationFee = 90.00m,
                            FirstName = "Elena",
                            LastName = "Vasquez",
                            LicenseNumber = "VET-0005",
                            Specialty = "ExoticAnimals",
                            YearsOfExperience = 9
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PawCare.Server.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PawCare.Server.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawCare.Server.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PawCare.Server.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PawCare.Server.Entities.Appointment", b =>
                {
                    b.HasOne("PawCare.Server.Entities.Pet", "Pet")
                        .WithMany("Appointments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veterinarian", "Veterinarian")
                        .WithMany("Appointments")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("PawCare.Server.Entities.Pet", b =>
                {
                    b.HasOne("PetOwner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PetOwner", b =>
                {
                    b.HasOne("PawCare.Server.Entities.ApplicationUser", "ApplicationUser")
                        .WithOne("PetOwner")
                        .HasForeignKey("PetOwner", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Veterinarian", b =>
                {
                    b.HasOne("PawCare.Server.Entities.ApplicationUser", "ApplicationUser")
                        .WithOne("Veterinarian")
                        .HasForeignKey("Veterinarian", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("PawCare.Server.Entities.ApplicationUser", b =>
                {
                    b.Navigation("PetOwner");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("PawCare.Server.Entities.Pet", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("PetOwner", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Veterinarian", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
